// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDffOoECe_qoAp0p9WXjqydLdvoJr5dzc',
    appId: '1:538512845950:web:a1b280707f697f12197c2f',
    messagingSenderId: '538512845950',
    projectId: 'example-app-3db94',
    authDomain: 'example-app-3db94.firebaseapp.com',
    storageBucket: 'example-app-3db94.appspot.com',
    measurementId: 'G-NVGWC0SLJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKm0Q7MLqSXxQ6VOIMAqMGrNvHNBJqOXQ',
    appId: '1:538512845950:android:5abf11d78184a280197c2f',
    messagingSenderId: '538512845950',
    projectId: 'example-app-3db94',
    storageBucket: 'example-app-3db94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYFtlV0F-KoE6Jyq8YMm7rSwAL1dulkKU',
    appId: '1:538512845950:ios:0138795ea1f3aeb5197c2f',
    messagingSenderId: '538512845950',
    projectId: 'example-app-3db94',
    storageBucket: 'example-app-3db94.appspot.com',
    iosClientId: '538512845950-98qoam6jdno4lnb6o1c0fvvffaid7861.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYFtlV0F-KoE6Jyq8YMm7rSwAL1dulkKU',
    appId: '1:538512845950:ios:461da9c60056afc4197c2f',
    messagingSenderId: '538512845950',
    projectId: 'example-app-3db94',
    storageBucket: 'example-app-3db94.appspot.com',
    iosClientId: '538512845950-h428vctehh1bm13n6et0phh3hj4kjvbs.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseExample.RunnerTests',
  );
}
